server:
  port: 8080

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://192.168.10.130:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.qianqiangongzi.entity

#showSql
logging:
  level:
    com:
      qianqiangongzi:
        dto: debug